build: off

platform:
  - x64

environment:
  matrix:
    - TOXENV: "py27"
    - TOXENV: "py36"

install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\MinGW\bin;%PATH%
  - cmd: pip install tox

test_script:
  - cmd: tox

notifications:
  - provider: Slack
    incoming_webhook:
      secure: E9H0SU0Ju7WLDvgxsV8cs3J62T3nTTX7QkEjsczN0Sto/c9hWkVfhc5gGWUkxhlD975cokHByKGJIdwYwCewqOI+7BrcT8U+nlga4Uau7J8=
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
