language: python

matrix:
  include:
    - os: linux
      sudo: false
      python: 2.7
      env: TOX_ENV=docs
    - os: linux
      sudo: false
      python: 2.7
      env: TOX_ENV=lint
    - os: linux
      sudo: required
      python: 2.7
      env: TOX_ENV=py27
    - os: osx
      language: generic
      env: TOX_ENV=skipexamples

install:
  - git submodule update --init --recursive
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip install -U tox; else pip install -U tox; fi

  # ChipKIT issue: install 32-bit support for GCC PIC32
  - if [[ "$TOX_ENV" == "py27" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libc6-i386; fi

script:
  - tox -e $TOX_ENV

after_success:
  - if [[ "$TOX_ENV" == "py27" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tox -e coverage; fi
  - if [[ "$TOX_ENV" == "py27" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false

  slack:
    rooms:
      secure: JD6VGfN4+SLU2CwDdiIOr1VgwD+zbYUCE/srwyGuHavnjIkPItkl6T6Bn8Y4VrU6ysbuKotfdV2TAJJ82ivFbY8BvZBc7FBcYp/AGQ4FaCCV5ySv8RDAcQgdE12oaGzMdODiLqsB85f65zOlAFa+htaXyEiRTcotn6Y2hupatrI=
    on_failure: always
    on_success: change
